typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#007b5f'
    - '#c8e2dc'
    - '#ee9f46'
    - '#f6c795'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25
analytics:
  google: null
  facebook: null
  twitter: null
name: Kakunje
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Kakunje Ayurveda
description: Your Home of Wellness
purpose: []
